### ISSUE TITLE
用supervisor管理,启动时报错?

### ISSUE THREAD

**Issue by feng99** [iwannay/jiacrontab#78]
**Describe the bug**

```
[program:jiaCrontabAdmin]
command=/data/soft/jiacrontab/jiacrontab_admin/jiacrontab_admin 
user=www 
```

报错日志
```
goroutine 1 [running]:
jiacrontab/jiacrontab_admin.(*Config).loadConfig(0xc0000a6230, 0xd41546, 0x16, 0x203000)
	/opt/goproject/src/jiacrontab/jiacrontab_admin/config.go:151 +0x178
jiacrontab/jiacrontab_admin.(*Config).Resolve(0xc0000a6230)
	/opt/goproject/src/jiacrontab/jiacrontab_admin/config.go:72 +0x81
main.parseFlag(0xc0000a6230, 0xc00000f240)
	/opt/goproject/src/jiacrontab/app/jiacrontab_admin/main.go:50 +0x3fe
main.main()
	/opt/goproject/src/jiacrontab/app/jiacrontab_admin/main.go:67 +0x21f










panic: open ./jiacrontab_admin.ini: permission denied

goroutine 1 [running]:
jiacrontab/jiacrontab_admin.(*Config).loadConfig(0xc0000a62d0, 0xd41546, 0x16, 0x203000)
	/opt/goproject/src/jiacrontab/jiacrontab_admin/config.go:151 +0x178
jiacrontab/jiacrontab_admin.(*Config).Resolve(0xc0000a62d0)
	/opt/goproject/src/jiacrontab/jiacrontab_admin/config.go:72 +0x81
main.parseFlag(0xc0000a62d0, 0xc00000f1c0)
	/opt/goproject/src/jiacrontab/app/jiacrontab_admin/main.go:50 +0x3fe
main.main()
	/opt/goproject/src/jiacrontab/app/jiacrontab_admin/main.go:67 +0x21f
panic: open ./jiacrontab_admin.ini: permission denied


```

**Comment by iwannay** [comment]
你配置的权限问题，和jiacrontab本身没有关系
